######################################################################
# Automatically generated by qmake (2.01a) dim. nov. 15 22:38:30 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src
QT += xml

# Input
HEADERS += src/Data.hpp src/View.hpp
SOURCES += src/Data.cpp src/main.cpp src/View.cpp

# Output
OBJECTS_DIR = src
DESTDIR = build
